1252. Cells with Odd Values in a Matrix
GrishinAnton/algorithms pull request #42
Opened 2020-05-09 09:53 UTC by GrishinAnton

Что то так и не разобрался что тут сделать надо...Какое-то смутное описание задачи

2020-05-09 14:42 UTC, vitkarpov commented
![image](https://user-images.githubusercontent.com/3001791/81476669-cda2eb00-921b-11ea-8480-19dcc688261d.png)

Для всех строк и столбцов в `indexes` надо увеличить на 1 все элементы в данном столбце и строке. В данном примере:

(0, 1) → Увеличиваем все элементы на 1 в строке 0 (получается первая строка всех единиц), увеличиваем все элементы на 1 в столбце (получается второй столбец единиц и т.к. в первой строке уже были единице — получаем двойку в точке (0, 1))
(1, 1) → аналогичная логка.

2020-05-10 12:14 UTC, GrishinAnton commented
@vitkarpov 
Написал решение на куче циклов:)
Получил сложность О(n * m)
где  n - это проход по массиву
m - это проход уже по элементам массива в самом конце, где вложенный цикл.

Наверное можно за  О(n) сделать, если по другому структурировать массивы7

2020-05-10 12:39 UTC, vitkarpov requested changes
По идее, решение должно быть рабочим, однако сложность `O(k*(n + m)*n*m)`, где `n`,`m` — размеры матрицы, а `k` — длина массива с индексами, плюс `O(n * m)` дополнительной памяти.

Можно быстрее, за `O(k + n * m)` и `O(n + m)` дополнительной памяти сделать. Обрати внимание, что ты делаешь плюс один для каждому элементу определённой строки и столбца. Можно завести просто два вектора: для строк и столбцов, куда складывать информацию «об этом плюс один», грубо говоря, если в векторе для строк на позиции k-ой лежит три, это значит что **всем** элементам этой строки надо прибавить три, т.е. это всего одно число, а не реальная строка из троек в матрице.

2020-05-11 12:05 UTC, GrishinAnton commented
Что-то не могу пока представить эту структуру....

2020-05-11 14:23 UTC, vitkarpov commented
<img width="252" alt="Screen Shot 2020-05-11 at 5 22 58 PM" src="https://user-images.githubusercontent.com/3001791/81572615-18536d00-93ac-11ea-9e8b-44144a95cf14.png">

Поможет такое?

2020-05-12 18:07 UTC, GrishinAnton commented
> <img alt="Screen Shot 2020-05-11 at 5 22 58 PM" width="252" src="https://user-images.githubusercontent.com/3001791/81572615-18536d00-93ac-11ea-9e8b-44144a95cf14.png">
> 
> Поможет такое?

Да, я о таком тоже подумал, но меня тормазнул подсчет потом нечетных чисел. 
Получается если у нас row 2 и cols 3

На первой row 2 значение + cols
А на первой row это же значение не увеличивается.

И тут я не придумал как это в такой структура разложить...

2020-05-12 18:14 UTC, GrishinAnton commented
А стоп, кажется я затупил. У нас такого не может быть.
Ведь всему cols увеличивается...

2020-05-13 03:47 UTC, GrishinAnton commented
@vitkarpov 
Обновил решение, вроде сложность получилась как ты писал.
`O(k + n * m) и O(n + m)`

2020-05-13 04:37 UTC, vitkarpov approved these changes
Именно так, да.

2020-05-13 04:37 UTC, vitkarpov commented on array/1252.cells-with-odd-values-in-a-matrix.js
> +// };
Опять коммент, зачем 😄

2020-05-13 05:44 UTC, merged